### ISSUE TITLE
'uint8_t' error in Fedora 38

### ISSUE THREAD

**Issue by ZAQraven** [zynaddsubfx/zyn-fusion-build#107]
Compiling Zyn-fusion in Mode release resulting in two errors.

[ 36%] Building CXX object src/CMakeFiles/zynaddsubfx_core.dir/Misc/Bank.cpp.o
In file included from /home/zaqraven/zyn-fusion-build/src/zynaddsubfx/src/Misc/Bank.cpp:16:
/home/zaqraven/zyn-fusion-build/src/zynaddsubfx/src/Misc/Bank.h:62:21: error: ‘uint8_t’ has not been declared
   62 |         void setMsb(uint8_t msb);
      |                     ^~~~~~~
/home/zaqraven/zyn-fusion-build/src/zynaddsubfx/src/Misc/Bank.h:63:21: error: ‘uint8_t’ has not been declared
   63 |         void setLsb(uint8_t lsb);
      |                     ^~~~~~~
/home/zaqraven/zyn-fusion-build/src/zynaddsubfx/src/Misc/Bank.h:111:9: error: ‘uint8_t’ does not name a type
  111 |         uint8_t bank_msb;
      |         ^~~~~~~
/home/zaqraven/zyn-fusion-build/src/zynaddsubfx/src/Misc/Bank.h:21:1: note: ‘uint8_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
   20 | #include "Config.h"
  +++ |+#include <cstdint>
   21 | 
/home/zaqraven/zyn-fusion-build/src/zynaddsubfx/src/Misc/Bank.h:112:9: error: ‘uint8_t’ does not name a type
  112 |         uint8_t bank_lsb;
      |         ^~~~~~~
/home/zaqraven/zyn-fusion-build/src/zynaddsubfx/src/Misc/Bank.h:112:9: note: ‘uint8_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/zaqraven/zyn-fusion-build/src/zynaddsubfx/src/Misc/Bank.cpp: In constructor ‘zyn::Bank::Bank(zyn::Config*)’:
/home/zaqraven/zyn-fusion-build/src/zynaddsubfx/src/Misc/Bank.cpp:62:21: error: class ‘zyn::Bank’ does not have any field named ‘bank_msb’
   62 |     db(new BankDb), bank_msb(0), bank_lsb(0)
      |                     ^~~~~~~~
/home/zaqraven/zyn-fusion-build/src/zynaddsubfx/src/Misc/Bank.cpp:62:34: error: class ‘zyn::Bank’ does not have any field named ‘bank_lsb’
   62 |     db(new BankDb), bank_msb(0), bank_lsb(0)
      |                                  ^~~~~~~~
/home/zaqraven/zyn-fusion-build/src/zynaddsubfx/src/Misc/Bank.cpp: In member function ‘int zyn::Bank::loadbank(std::string)’:
/home/zaqraven/zyn-fusion-build/src/zynaddsubfx/src/Misc/Bank.cpp:239:5: error: ‘bank_msb’ was not declared in this scope; did you mean ‘banks’?
  239 |     bank_msb = 0;
      |     ^~~~~~~~
      |     banks
/home/zaqraven/zyn-fusion-build/src/zynaddsubfx/src/Misc/Bank.cpp: At global scope:
/home/zaqraven/zyn-fusion-build/src/zynaddsubfx/src/Misc/Bank.cpp:439:6: error: no declaration matches ‘void zyn::Bank::setMsb(uint8_t)’
  439 | void Bank::setMsb(uint8_t msb)
      |      ^~~~
/home/zaqraven/zyn-fusion-build/src/zynaddsubfx/src/Misc/Bank.h:62:14: note: candidate is: ‘void zyn::Bank::setMsb(int)’
   62 |         void setMsb(uint8_t msb);
      |              ^~~~~~
/home/zaqraven/zyn-fusion-build/src/zynaddsubfx/src/Misc/Bank.h:28:7: note: ‘class zyn::Bank’ defined here
   28 | class Bank
      |       ^~~~
/home/zaqraven/zyn-fusion-build/src/zynaddsubfx/src/Misc/Bank.cpp:445:6: error: no declaration matches ‘void zyn::Bank::setLsb(uint8_t)’
  445 | void Bank::setLsb(uint8_t lsb)
      |      ^~~~
/home/zaqraven/zyn-fusion-build/src/zynaddsubfx/src/Misc/Bank.h:63:14: note: candidate is: ‘void zyn::Bank::setLsb(int)’
   63 |         void setLsb(uint8_t lsb);
      |              ^~~~~~
/home/zaqraven/zyn-fusion-build/src/zynaddsubfx/src/Misc/Bank.h:28:7: note: ‘class zyn::Bank’ defined here
   28 | class Bank
      |       ^~~~
make[3]: *** [src/CMakeFiles/zynaddsubfx_core.dir/build.make:468: src/CMakeFiles/zynaddsubfx_core.dir/Misc/Bank.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:1526: src/CMakeFiles/zynaddsubfx_core.dir/all] Error 2
make[1]: *** [Makefile:146: all] Error 2
make[1]: Leaving directory '/home/zaqraven/zyn-fusion-build/build/build-zynaddsubfx-linux-release'
make: *** [Makefile.linux.mk:20: build_zynaddsubfx] Error 2

**Comment by fundamental** [comment]
This issue should be resolved by https://github.com/zynaddsubfx/zynaddsubfx/commit/f384d92486d6b515cb628d0f52008a9e03341d8c

**Comment by ZAQraven** [comment]
I see, fixed. But, it was not only bank.h nor bank.cpp. It also occurred on:
~/zyn-fusion-build/src/zynaddsubfx/src/Nio/NulEngine.cpp
~/zyn-fusion-build/src/zynaddsubfx/src/Nio/InMgr.cpp
~/zyn-fusion-build/src/zynaddsubfx/src/Nio/EngineMgr.cpp
~/zyn-fusion-build/src/zynaddsubfx/src/Nio/Nio.cpp
~/zyn-fusion-build/src/zynaddsubfx/src/Nio/OssEngine.cpp
~/zyn-fusion-build/src/zynaddsubfx/src/Nio/MidiIn.cpp

Each of them must given (before the list):

#include <cstdint>
#include <stdint.h>

**Comment by fundamental** [comment]
Those issues should in theory be fixed with the most recent commit.
