### ISSUE TITLE
lo/lo_types.h: No such file or directory

### ISSUE THREAD

**Issue by damarindra** [zynaddsubfx/zyn-fusion-build#16]
Hello,
Thanks for the hardwork for the great UI!
I'm trying to compile into windows version using Linux Mint 18.1 64bit (Ubuntu 16.04), but I got this error. Anyway to fix this?
`/home/damar/zyn-fusion-build/zynaddsubfx/rtosc/include/rtosc/port-checker.h:36:25: fatal error: lo/lo_types.h: No such file or directory
compilation terminated.
rtosc/CMakeFiles/rtosc-cpp.dir/build.make:263: recipe for target 'rtosc/CMakeFiles/rtosc-cpp.dir/src/cpp/port-checker.cpp.obj' failed
make[2]: *** [rtosc/CMakeFiles/rtosc-cpp.dir/src/cpp/port-checker.cpp.obj] Error 1
CMakeFiles/Makefile2:539: recipe for target 'rtosc/CMakeFiles/rtosc-cpp.dir/all' failed
make[1]: *** [rtosc/CMakeFiles/rtosc-cpp.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
ERROR: 'make' failed`

**Comment by fundamental** [comment]
@JohannesLorenz There shouldn't be liblo includes in anything within rtosc outside of compatibility tests. That's waaaay out-of-scope. Please remove this code and if it's needed put it in a different repository.

 From the rtosc readme's project goals: "* [rtosc will] Keep networking outside of project scope".

@damarindra You should be able to build if you install the dependencies first. For ZynAddSubFX's core that includes 'liblo'.

**Comment by damarindra** [comment]
The required dependencies is installed at my computer, liblo is already the newest version (0.28-5). I've been trying compile to linux and it's works fine tho, windows version is always fail.

**Comment by fundamental** [comment]
@JohannesLorenz Can you update this issue after making the changes? They should solve the issue with the windows build once the test builds only when rtosc finds liblo (Zyn should still find liblo, but in a slightly different manner).

**Comment by JohannesLorenz** [comment]
@damarindra @fundamental I'll push the fix ASAP (in the next hour).

**Comment by JohannesLorenz** [comment]
@damarindra It should work now with the current master of zynaddsubfx (don't forget to do a `git submodule update`). Can you please retry?

**Comment by fundamental** [comment]
If it's the normal build scripts it should remove the old version and do a full git checkout, so I don't think any git submodule update would be needed.

**Comment by damarindra** [comment]
thanks! it works flawlessly! calling ruby build-windows.rb is just fine.
