### ISSUE TITLE
Building on Linux (Debian stretch) failed

### ISSUE THREAD

**Issue by merspieler** [zynaddsubfx/zyn-fusion-build#17]
when running `ruby build-linux.rb` I get this error msg:
``` bash
Looking For pkg config modules
-- Checking for module 'ntk'
--   No package 'ntk' found
-- Checking for module 'ntk_images'
--   No package 'ntk_images' found
-- Checking for module 'fftw3'
--   No package 'fftw3' found
CMake Error at rtosc/cmake/ColorMessage.cmake:53 (_message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindPkgConfig.cmake:415 (message)
  /usr/share/cmake-3.7/Modules/FindPkgConfig.cmake:588 (_pkg_check_modules_internal)
  src/CMakeLists.txt:33 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "/home/user/synth/zyn-fusion-build/build-zynaddsubfx-demo/CMakeFiles/CMakeOutput.log".
See also "/home/user/synth/zyn-fusion-build/build-zynaddsubfx-demo/CMakeFiles/CMakeError.log".
ERROR: 'cmake ../zynaddsubfx/ -DGuiModule=zest -DDemoMode=true -DCMAKE_INSTALL_PREFIX=/usr' failed
```

[CMakeError.log](https://github.com/zynaddsubfx/zyn-fusion-build/files/2086884/CMakeError.log)
[CMakeOutput.log](https://github.com/zynaddsubfx/zyn-fusion-build/files/2086885/CMakeOutput.log)

**Comment by fundamental** [comment]
On 06-09, merspieler wrote:
> -- Checking for module 'fftw3'
> --   No package 'fftw3' found
> CMake Error at rtosc/cmake/ColorMessage.cmake:53 (_message):
>   A required package was not found

If you're building the linux version, please ensure build dependencies
are installed includeing fftw3.

**Comment by merspieler** [comment]
I've installed fftw3 via apt and it shows me that version 3.3.5-3 is installed. While installing apt said it's choosing libfftw3-3 instead of fftw3... the build still fails

**Comment by merspieler** [comment]
I've found the problem with fftw3... i needed to install the `-dev` package.

A dependency list would be good to have...

**Comment by fundamental** [comment]
https://github.com/zynaddsubfx/zyn-fusion-build/wiki/Building-on-Linux  should cover that unless I'm mistaken
