### ISSUE TITLE
Ardour crashing when loading Zyn-Fusion

### ISSUE THREAD

**Issue by brylie** [zynaddsubfx/zyn-fusion-build#18]
I can load ZynFusion into a track in Ardour. However, when I try to open the ZynFusion UI, Ardour crashes to desktop.

The ZynFusion UI works in standalone.

OS: Ubuntu (KDE Neon)
Ardour version: 5

**Comment by fundamental** [comment]
Thanks for the report.
To get a better idea of where the problem may exist can you follow:
https://ardour.org/debugging_ardour

From there you should be able to generate a backtrace pointing out where
the error may be.

Additionally, to confirm you have built Zyn-Fusion from this
zyn-fusion-build set of build scripts, right?

**Comment by brylie** [comment]
I downloaded Zyn-Fusion from the Gumroad link.

**Comment by brylie** [comment]
I tried the steps on the debugging page for running gdb on a version downloaded from ardour.org, and got the following messge:

```
Reading symbols from /opt/Ardour-5.12.0/bin/ardour-5.12.0...(no debugging symbols found)...done.
```

**Comment by brylie** [comment]
Here is the output from `gdb`:

```
ARNING: this host does not send sample-rate information for LV2 UIs, using 44100 as fallback (this could be wrong)
[INFO] Opened the zynaddsubfx UI...
[INFO] Ready to run
[INFO:Zyn] zest_open()
[INFO:Zyn] Found Assets at /opt/zyn-fusion/
[INFO:Zyn] Creating MRuby Interpreter...
[INFO] setting up runner
[debug] parsing json file
[INFO] init gl
[INFO] loading fonts
[INFO] window width=1181
[INFO] window height=659
[INFO] init window
Time for a fast load is 6.395ms load(0.007) class(0.001) spawn(6.387)...
[INFO] doing setup
[INFO] doing layout
[INFO] Running Layout Solver...
[INFO] launching program...
[INFO] ret code = 0
[ERROR] GLPSOL EXITED WITH ERROR CODE 1
[INFO] GLPK Solver finished...
[INFO] Read solution to layout...
[ERROR] The output file '/tmp/zest-w.txt' from glpsol was not found
[ERROR] This file is needed for layout
[ERROR] Please verify that there is a usable glpsol in the current directory

Thread 34 "ardour-5.12.0" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffbdcd5700 (LWP 11829)]
0x00007fffedf2ff90 in sord_find () from /opt/Ardour-5.12.0/lib/libsord-0.so.0
```

**Comment by fundamental** [comment]
if it's talking about the GLPK solver, then you have downloaded a very old
version of zyn-fusion from gumroad. I'd recommend grabbing a newer version
from gumroad and you should be all set.

**Comment by brylie** [comment]
Aah yeah, I downloaded 3.0.0 from the top of the list. I will try with * zyn-fusion-linux-64bit-3.0.3-release.tar*

**Comment by brylie** [comment]
Jep, the newer version works. Thanks for your help @fundamental :-)
