### ISSUE TITLE
(minor change) flag -a (append) in build-linux.rb

### ISSUE THREAD

**Issue by arkenidar** [zynaddsubfx/zyn-fusion-build#19]
I propose to use the flag append otherwise the content will be of a single line in place of 3 lines... ;)
```
cmd "echo 'Version #{CurrentVersion}' | sudo tee -a /opt/zyn-fusion/VERSION"
cmd "echo 'Build on'                  | sudo tee -a /opt/zyn-fusion/VERSION"
cmd "echo `date`                      | sudo tee -a /opt/zyn-fusion/VERSION"
```
try it as I did... ;)

**Comment by fundamental** [comment]
Fixed via https://github.com/zynaddsubfx/zyn-fusion-build/commit/9a05c8b4dcac624335f98b5f9aba1904316806cf
