### ISSUE TITLE
broken symbolic link

### ISSUE THREAD

**Issue by arkenidar** [zynaddsubfx/zyn-fusion-build#20]
* I get this error:
> -- Installing: /usr/lib/lv2/ZynAddSubFX.lv2presets
> CMake Error at cmake_install.cmake:71 (file):
>   file INSTALL cannot make directory "/usr/lib/lv2/ZynAddSubFX.lv2presets":
>   Too many levels of symbolic links
> 
> 
> Makefile:128: recipe for target 'install' failed
> make: *** [install] Error 1
> ERROR: 'sudo make install' failed

* I enquire about it and discover...
> file /usr/lib/lv2/ZynAddSubFX.lv2presets
> /usr/lib/lv2/ZynAddSubFX.lv2presets: broken symbolic link to /opt/zyn-fusion/ZynAddSubFX.lv2presets

* I proceed to fix it quick and dirty
> sudo rm /usr/lib/lv2/ZynAddSubFX.lv2presets

* then I can build again
>ruby build-linux.rb

**Comment by fundamental** [comment]
That's a result of installing the zyn-fusion built tarball, then partially removing it, and then trying to install zyn again.

As long as the uninstall is done completely, then this is a non-problem.
