### ISSUE TITLE
You could add dependencies for Fedora/Suse/CentOS ... in the Wiki

### ISSUE THREAD

**Issue by BrunoVernay** [zynaddsubfx/zyn-fusion-build#22]
I successfully build on Fedora 29 with the following packages. (I could try to make a RPM on COPR https://copr.fedorainfracloud.org/coprs/fulltext/?fulltext=zyn-fusion but it is easier and safer to compile from source.)
```
sudo dnf install @"C Development Tools and Libraries" git ruby libtool mxml-devel automake cmake fftw-devel jack-audio-connection-kit-devel liblo-devel zlib-devel alsa-lib-devel  libX11-devel  mesa-libGL-devel cairo-devel fontconfig-devel  python bison
```
Note: @"C Development Tools and Libraries"  includes `bison`, `make`, `gcc` and other stuff, maybe it could be optimized.  But at least it is a start.

**Comment by fundamental** [comment]
It would be great to expand build instructions to make it simpler on
other distros.
From what I recall, the wiki should be publicly editable, so if you
have a package list then I'd recommend adding it with any caveats about
your personal setup.

**Comment by BrunoVernay** [comment]
I see no way to edit/create Wiki pages  and  GitHub features no Pull Request for them.
In fact, creating a `BUILD.md` next to the `README.md` might be easier to deal with :-)

**Comment by fundamental** [comment]
There should be an edit button in the upper right of each wiki page. I don't think there even is an option for collaborator only wiki's. From the github repo setting page:

> GitHub Wikis is a simple way to let others contribute content. Any GitHub user can create and edit pages to use for documentation, examples, support, or anything you wish.

**Comment by BrunoVernay** [comment]
I checked again, but there is no `Edit` button anywhere in the page. 
The best I can do is to see the 6 revisions by Victoria, that's all. No Edit, No create, No delete.

**Comment by fundamental** [comment]
As it turns out I'm in need of a new pair of glasses.
![wiki](https://user-images.githubusercontent.com/766621/50187017-c4de0c00-02ea-11e9-9f80-269ebf01bf68.png)

I have now fixed the setting.

**Comment by BrunoVernay** [comment]
OK, done. Hope there will be no SPAM and defacing ...
