### ISSUE TITLE
Master Volume not Restored under NSM

### ISSUE THREAD

**Issue by 0mk** [zynaddsubfx/zyn-fusion-build#32]
When running the built copy of zynaddsubfx under NSM (Non Session Manager), changes to the master volume are saved correctly when saving or closing a session. However, when opening a session, changes to the master volume are not restored as they should be.

**Comment by fundamental** [comment]
Looking at the NSM code all it should be doing on save is saving a .xmz file and on open it should simply load the .xmz file. Are you able to replicate the issue by loading/saving an .xmz file directly?

**Comment by 0mk** [comment]
Thanks for looking into this issue. I can confirm that when running zyn-fusion build directly (without NSM), if I adjust the master volume and then "save master", it will save the master volume correctly. However, if I quit, then launch zyn-fusion again and "load master" from the saved file, it does NOT restore the master volume.

**Comment by fundamental** [comment]
Confirmed, Replicated, and fixed via https://github.com/zynaddsubfx/zynaddsubfx/commit/6e838ba43db848a0645e96d8609310b23db7ea7b
