### ISSUE TITLE
Troubles when building for Windows

### ISSUE THREAD

**Issue by kanafutile** [zynaddsubfx/zyn-fusion-build#33]
So, I installed Ubuntu 18.04 VM to build Zyn-Fusion for Windows (had less luck with building using `build-mingw64.sh`).

Cloned the repository, ran `ruby build-windows.rb`.

### the first trouble:
The building process failed:
```
Changing directory to deps/mruby-dir-glob
git apply ../../../mruby-dir-glob-no-process.patch
Changing directory to ../mruby-io
git apply ../../../mruby-io-libname.patch
Changing directory to ../../mruby
git apply ../../mruby-float-patch.patch
error: patch failed: src/backtrace.c:209
error: src/backtrace.c: patch does not apply
ERROR: 'git apply ../../mruby-float-patch.patch' failed
```

So, I tried to patch `backtrace.c` myself, by just adding the `char superhack[1024*20];` and removed all signs of `backtrace.c` from `mruby-float-patch.patch`. Reran `ruby build-windows.rb`.

### the second trouble:

<details><summary>The building process failed:</summary>

```
LD    build/host/bin/mirb 
/usr/bin/ld: cannot find -lWs2_32
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lWs2_32
collect2: error: ld returned 1 exit status
rake aborted!
Command failed with status (1): [gcc -LC:/Windows/system -o /home/zyn-build...]
/home/zyn-builder/building/zyn-fusion-build/mruby-zest-build/mruby/lib/mruby/build/command.rb:31:in `_run'
/home/zyn-builder/building/zyn-fusion-build/mruby-zest-build/mruby/lib/mruby/build/command.rb:36:in `rescue in _run'
/home/zyn-builder/building/zyn-fusion-build/mruby-zest-build/mruby/lib/mruby/build/command.rb:32:in `_run'
/home/zyn-builder/building/zyn-fusion-build/mruby-zest-build/mruby/lib/mruby/build/command.rb:210:in `run'
/home/zyn-builder/building/zyn-fusion-build/mruby-zest-build/mruby/Rakefile:79:in `block (4 levels) in <top (required)>'

Caused by:
Command failed with status (1): [gcc -LC:/Windows/system -o /home/zyn-build...]
/home/zyn-builder/building/zyn-fusion-build/mruby-zest-build/mruby/lib/mruby/build/command.rb:33:in `_run'
/home/zyn-builder/building/zyn-fusion-build/mruby-zest-build/mruby/lib/mruby/build/command.rb:210:in `run'
/home/zyn-builder/building/zyn-fusion-build/mruby-zest-build/mruby/Rakefile:79:in `block (4 levels) in <top (required)>'
Tasks: TOP => default => all => /home/zyn-builder/building/zyn-fusion-build/mruby-zest-build/mruby/bin/mirb => /home/zyn-builder/building/zyn-fusion-build/mruby-zest-build/mruby/build/host/bin/mirb
(See full trace by running task with --trace)
Makefile:37: recipe for target 'windows' failed
make: *** [windows] Error 1
ERROR: 'make windows' failed
```

</details>
My question is: how to avoid these troubles?

**Comment by fundamental** [comment]
Thanks for pointing this out.

The mruby-float-patch.patch should likely be updated since the version
of the MRuby VM has changed relatively recently.
That should be a relatively easy fix.

As per the matter of -lWs2_32, it's going to be a matter of finding the
rake file which is linking to Ws2_32 and patching it in the same manner
as mruby-io-libname.patch.

Let me know if you have a chance to find the additional patch needed,
otherwise I'll try to address it next time I have an ubuntu VM up and
running.

**Comment by kanafutile** [comment]
I am going to be in the hospital for the next few days, so won't be able to do that. Thanks for the effort.

**Comment by DerAndere1** [comment]
I had the same error
`error: src/backtrace.c: patch does not apply`
when running build-mingw64.sh under Windows 10 64bit with MSYS2/mingw64. The same procedure worked a year ago. I have near 0 experience with building software for PC but thought it must be possible to modify the build-mingw64.sh file so it uses older versions?

**Comment by gatesphere** [comment]
+1 to this -- encountered the same backtrace patch issue when building for mingw64.  I don't know enough C to fix this properly.  I've removed the backtrace.c portion from the patch file and will see if it compiles that way.

**Comment by DerAndere1** [comment]
@gatesphere which lines did you comment out exactly to get rid of the backtrace.c patch? Thanks.

**Comment by gatesphere** [comment]
@DerAndere1 

I removed lines 33-110 from the mruby-float-patch.patch file (https://github.com/zynaddsubfx/zyn-fusion-build/blob/master/mruby-float-patch.patch#L33-L110)

Did the normal ./build-mingw64.sh process, watched it fail at the end, then did:

    $ cd /wherever/the/mruby/directory/is (sorry, not at the machine I built it on)

Inserted `char superhack[1024*20];` into the file (below the `#ifndef MRB_DISABLE_STDIO` line, IIRC)

    $ make clean && rm deps/libuv-win.a && make setupwin && make builddepwin
    $ cd ..
    $ ./z/build-package.sh demo true
    $ ./z/build-package.sh release false

**Comment by mattiabruni** [comment]
I'm having problems too in applying the patches to ruby; I mostly use Windows 10, but I've had the same error under Ubuntu.

`$ cd deps/mruby-dir-glob && git apply ../../../mruby-dir-glob-no-process.patch
 error: patch non riuscita: mrbgem.rake:8
error: mrbgem.rake: la patch non si applica correttamente`

(patch doesn't apply)

Subsequent patches fail in the same way.

**Comment by ZLau92** [comment]
It doesn't seem to have anything to do with the build environment. The patch is definitely just for the old version of mruby.

The patch applies cleanly when you use an older mruby in place of the current submodule that's checked out.
Namely, this version: https://github.com/mruby/mruby/releases/tag/1.3.0

**Comment by ZLau92** [comment]
I guess it'd be important to note that even with the patches all cleanly applying, I still hit the sys/wait.h not found problem once it gets toward the mruby-process dependency.

**Comment by ZLau92** [comment]
I managed to get the original patch to apply to an old copy of mruby, but it didn't fix the sys/wait.h error on compile.

All the same, I did go through and update the backtrace file according to the old patch. Result attached.
[mruby-float-patch.zip](https://github.com/zynaddsubfx/zyn-fusion-build/files/3873092/mruby-float-patch.zip)

I was able to get zyn-fusion to build by removing the mruby-process submodule from mruby-zest-build. But it gives me a blank black window when I start it.
Not too knowledgeable about mruby, so I'm not sure how to approach. But it would seem that something about the mruby-process dependency would need to change because the sys/wait.h include file can't be satisfied by a mingw build environment.
But I'd be happy to know if a workaround exists :-)

**Comment by SeleDreams** [comment]
I still got the error so I think it still didn't get fixed

**Comment by lynerlok** [comment]
Yes the same today...

**Comment by lynerlok** [comment]
I try the solution by @gatesphere but I have an error when I execute  ./build-mingw64.sh :
pacman is not found ( it's logical i'm on ubuntu container not in arch )

**Comment by PaulHaeger** [comment]
The build-mingw64.sh is meant for the mingw64.exe shell that is supplied in msys2. For Ubuntu you should use the build-windows.rb

**Comment by SeleDreams** [comment]
I ended up buying the prebuilt v in the end, but to be fair I wonder if the devs aren't voluntarily not fixing the build scripts in order to force people to buy the paid binaries

**Comment by lynerlok** [comment]
@PaulHaeger Ho... Ok i'm stupid sorry...

**Comment by DerAndere1** [comment]
@SeleDreams: No, your point is not valid. Everyone could send in pull requests to fix this but no complete fix was provided by others. Looks  like the maintainer and others are actively working on this. See open pull request 39

**Comment by SeleDreams** [comment]
> 
> 
> @SeleDreams: No, your point is not valid. Everyone could send in pull requests to fix this but no complete fix was provided by others. Looks like the maintainer and others are actively working on this. See open pull request 39

The reason I was thinking this is that the windows build scripts were broken since a long time, almost a year I think.
And prebuilt versions wise meanwhile they still posted windows builds making it kind of obvious they have working windows build scripts

**Comment by fundamental** [comment]
@SeleDreams You're making the assumption that I'm hiding something from the public. What is done at this stage is done in the open. Things certainly can move slowly as life is busy and trying to maintain build systems for multiple platforms, multiple plugin hosts, manage the community, offer support on multiple platforms, etc is time consuming. If you're interested in seeing the development speed of the project increase, community involvement (as outlined at https://zynaddsubfx.sourceforge.io/contribute.html ) is usually the path forward for this project as well as most other open source projects.

**Comment by ZLau92** [comment]
Hey folks. Yeah, I haven't had time to follow through on the requested
changes to my pull request.
But you can check out and build my fork, assuming nothing huge has changed
since November.

**Comment by fundamental** [comment]
Should be resolved.
