### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by ErikKnowles** [zynaddsubfx/zyn-fusion-build#37]
I'm trying to build a Docker container using `docker build https://github.com/zynaddsubfx/zyn-fusion-build.git `

Partway through the build I get this:

>make setup
>cd deps              && wget -4 http://dist.libuv.org/dist/v1.9.1/libuv-v1.9.1.tar.gz && tar xvf libuv-v1.9.1.tar.gz
>/bin/sh: 1: wget: not found
>Makefile:66: recipe for target 'deps/libuv-v1.9.1' failed

Does this mean wget isn't included in the base image?

**Comment by ErikKnowles** [comment]
Confirmed; wget and python need to be installed w/ the apt-get statement

**Comment by fundamental** [comment]
As per the PR which added the docker build, I don't use docker, so while pull requests are welcome to fix or improve the docker based build, I cannot verify or debug any issues with it myself.

**Comment by ErikKnowles** [comment]
I'll do a pull request.
