### ISSUE TITLE
Failed Building for Windows in MinGW64 and Lubuntu

### ISSUE THREAD

**Issue by BW89** [zynaddsubfx/zyn-fusion-build#38]
Hello I tried building it for Windows and neither on Windows or Linux it would work. I tried many Workarounds found here in the issues tab but none worked. 
I don't need both variants to work as my only Goal is to get a working VST for using in Ableton Live

![error](https://user-images.githubusercontent.com/36115929/69356344-a2cfd500-0c83-11ea-83b1-5ec543f98c18.png)
![error2](https://user-images.githubusercontent.com/36115929/69356345-a2cfd500-0c83-11ea-960c-7522385217dc.png)

**Comment by ZLau92** [comment]
I was running into this issue, spent hours trying to figure out.
The thing that ended up working before running ./z/build release false was removing the mruby-process from the build-config and deps.

**Comment by BW89** [comment]
How do i do this?

**Comment by ZLau92** [comment]
Drop these files on top of a fresh copy of zyn-fusion-build, and overwrite the two already-existing files.
[build-mingw64-workaround.zip](https://github.com/zynaddsubfx/zyn-fusion-build/files/3878073/build-mingw64-workaround.zip)

**Comment by BW89** [comment]
Thank you that worked
