### ISSUE TITLE
Build fails for libzynaddsubfx_dssi

### ISSUE THREAD

**Issue by m4l3z** [zynaddsubfx/zyn-fusion-build#4]
On Ubuntu 16.04, with libfftw3-dev : 3.3.4-2ubuntu1
```
[ 60%] Linking CXX shared library libzynaddsubfx_dssi.so
/usr/bin/ld: /usr/local/lib/libfftw3.a(apiplan.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libfftw3.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src/CMakeFiles/zynaddsubfx_dssi.dir/build.make:202: recipe for target 'src/libzynaddsubfx_dssi.so' failed
make[2]: *** [src/libzynaddsubfx_dssi.so] Error 1
CMakeFiles/Makefile2:1598: recipe for target 'src/CMakeFiles/zynaddsubfx_dssi.dir/all' failed
make[1]: *** [src/CMakeFiles/zynaddsubfx_dssi.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
ERROR: 'make' failed
```

**Comment by fundamental** [comment]
zyn's cmake is finding fftw3 in /usr/local, which would not be the location for a ubuntu package. It looks like you have an old version of fftw that you built yourself installed to /usr/local . If you remove that version of fftw (and the associated pkgconfig file) then zyn should be able to find the version of fftw in /usr (i.e. /usr/lib/libfftw3.so )

**Comment by m4l3z** [comment]
Wow, correct and fast diagnostic ! Followed the steps and the rest of the compilation process went flawlessly.
