### ISSUE TITLE
HIDPI support

### ISSUE THREAD

**Issue by TatriX** [zynaddsubfx/zyn-fusion-build#40]
Hi! Can I somehow scale interface on 4k screen?

**Comment by fundamental** [comment]
In the standalone, yes. In the LV2, possibly (may be host and version dependent). In the VST version, not yet. If you're interested in working on the VST functionality let me know and I can point you in the right direction.

**Comment by TatriX** [comment]
> In the standalone, yes.
How can I do that?

I'm using ardour so that means LV2 I guess.

**Comment by TatriX** [comment]
Ah, standalone version resizes properly.

**Comment by ahstro** [comment]
I'm not seeing any way to scale the UI when using the LV2 plugin. Would be great to have this functionality for HiDPI screens.
