### ISSUE TITLE
How to build the new UI?

### ISSUE THREAD

**Issue by matthiasbeyer** [zynaddsubfx/zyn-fusion-build#44]
Hi,

I cannot find any information whatsoever about how to build the new UI. I always get the old UI... is there some possibly undocumented flag for the build to actually build the new UI?

**Comment by fundamental** [comment]
What are you currently doing in an attempt to build the new UI? After building what steps are you taking to run zyn?

**Comment by matthiasbeyer** [comment]
I build them from my [distro package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/audio/zynaddsubfx/default.nix) and load it in ardour, or start the binary (`zynaddsubfx`, as there is no `zyn-fusion` binary).

**Comment by fundamental** [comment]
If that's the case, then your distro package scripts are not building
the new UI and you'll have to build it yourself.
This repo contains scripts which walk through the whole process and
should be a good starting point.

**Comment by matthiasbeyer** [comment]
So from what I understand, the "zest" thing is the new UI that needs to be built before building zynaddsubfx itself?

**Comment by fundamental** [comment]
Not quite.
MRuby-Zest is the framework for the new UI and the zyn-fusion UI is the only
thing using the framework, so for the time being zest==zyn-fusion's gui.

You don't have to build zest before zynaddsubfx, you can build it
before/concurrently/after zynaddsubfx as the mruby-zest-build repo
produces the UI which exists somewhat separately from the audio
synthesis process.

**Comment by matthiasbeyer** [comment]
Ah okay. Anyways, I have to package that all for my distro so that it can be installed and used, and that'll be a hell of an effort. Thanks for your support, though, that helped understanding what I actually have to do.
