### ISSUE TITLE
Can't compile on ubuntu 18.04  AMD 64

### ISSUE THREAD

**Issue by zynmuse** [zynaddsubfx/zyn-fusion-build#47]
I'm trying the build on an AMD 64 system runing ubuntu 18.04

When I try to build zyn-fusion-build using the instructions  "Building on Linux" , the line
"ruby build-linux.rb" fails quite a long way into the build. 
I don't know ruby but problem appears to be in a "rake" file. see below;
(any help would be appreaciated!)
   

--------------------------------------------------------------------------------------------------compiler output----------
......
Building Zest in demo mode
Changing directory to mruby-zest-build
make clean
cd mruby             && MRUBY_CONFIG=../build_config.rb rake clean
Environment is:

false
rake aborted!
ArgumentError: Unknown pathmap specifier %2 in '/mnt/documents2/Documents/Development/ZynAddSubFx_SourceCode/zyn-fusion-build%200505/mruby-zest-build/mruby/build/host/src/%n'
/mnt/documents2/Documents/Development/ZynAddSubFx_SourceCode/zyn-fusion-build%200505/mruby-zest-build/mruby/src/mruby_core.rake:8:in `block (2 levels) in <top (required)>'
/mnt/documents2/Documents/Development/ZynAddSubFx_SourceCode/zyn-fusion-build%200505/mruby-zest-build/mruby/src/mruby_core.rake:6:in `map'
/mnt/documents2/Documents/Development/ZynAddSubFx_SourceCode/zyn-fusion-build%200505/mruby-zest-build/mruby/src/mruby_core.rake:6:in `block in <top (required)>'
/mnt/documents2/Documents/Development/ZynAddSubFx_SourceCode/zyn-fusion-build%200505/mruby-zest-build/mruby/lib/mruby/build.rb:13:in `instance_eval'
/mnt/documents2/Documents/Development/ZynAddSubFx_SourceCode/zyn-fusion-build%200505/mruby-zest-build/mruby/lib/mruby/build.rb:13:in `block in each_target'
/mnt/documents2/Documents/Development/ZynAddSubFx_SourceCode/zyn-fusion-build%200505/mruby-zest-build/mruby/lib/mruby/build.rb:12:in `each'
/mnt/documents2/Documents/Development/ZynAddSubFx_SourceCode/zyn-fusion-build%200505/mruby-zest-build/mruby/lib/mruby/build.rb:12:in `each_target'
/mnt/documents2/Documents/Development/ZynAddSubFx_SourceCode/zyn-fusion-build%200505/mruby-zest-build/mruby/src/mruby_core.rake:1:in `<top (required)>'
/mnt/documents2/Documents/Development/ZynAddSubFx_SourceCode/zyn-fusion-build%200505/mruby-zest-build/mruby/Rakefile:25:in `load'
/mnt/documents2/Documents/Development/ZynAddSubFx_SourceCode/zyn-fusion-build%200505/mruby-zest-build/mruby/Rakefile:25:in `<top (required)>'
(See full trace by running task with --trace)
Makefile:152: recipe for target 'clean' failed
make: *** [clean] Error 1
ERROR: 'make clean' failed

**Comment by fundamental** [comment]
Try renaming the build path.
It looks like 'rake' is having a problem parsing 'zyn-fusion-build%200505'.

**Comment by zynmuse** [comment]
Thank you for your help!
I changed the folder - got rid of the % and started again from the git clone.
It built perfectly from the instructions.
