### ISSUE TITLE
Windows build and mruby - zets

### ISSUE THREAD

**Issue by bird0912** [zynaddsubfx/zyn-fusion-build#5]
Hi, I got an email about zyn - fusion becoming open source, but it's my first time building this types of things, so... two questions:
1- How do I build zyn fusion with this source code?
2- How do I register it so the ten minutes limit dissapear?

Thank you for the good work and for your time
@fundamental

**Comment by fundamental** [comment]
> How do I build zyn fusion with this source code?

1. Setup a debian based Linux install (e.g. Ubuntu)
2. Run the build-windows.rb script from the https://github.com/zynaddsubfx/zyn-fusion-build repository

> How do I register it so the ten minutes limit disappears?

Either get a pre-built binary via https://gumroad.com/l/zyn-fusion or compile your own binary in release mode.

**Comment by bird0912** [comment]
Again, excuse my inexperience, how can I compile my own binary?

Thanks again :)

**Comment by fundamental** [comment]
You do that by building the source code via a Linux system using the build-windows.rb script from the https://github.com/zynaddsubfx/zyn-fusion-build repository which produces the windows binaries.
