### ISSUE TITLE
new bank browser can be confusing

### ISSUE THREAD

**Issue by grammoboy2** [zynaddsubfx/zyn-fusion-build#51]
When I search for a bank, it doesn't find anything. Type in rhodes... nothing, that's because I've selected a certain bank collection I guess. 

Maybe add a entry to the lists, 'All' or something. That would make it a bit more clear probably.

Just a quick thought, but at least it can be somewhat confusing. If and how you want to solve it, is up to you of course, you know the application best.

**Comment by fundamental** [comment]
Not an issue with the build scripts.

**Comment by grammoboy2** [comment]
Is this the way to deal with feedback? Why would I report issues next time?

**Comment by fundamental** [comment]
https://github.com/zynaddsubfx/zyn-fusion-issues/issues is the catchall for issues specific for the fusion GUI.

**Comment by grammoboy2** [comment]
ok
