### ISSUE TITLE
Trouble building for MSYS2 MinGW64

### ISSUE THREAD

**Issue by Kashouryo** [zynaddsubfx/zyn-fusion-build#54]
While running build-package.sh

[ 83%] Building CXX object src/CMakeFiles/zynaddsubfx_core.dir/Params/LFOParams.cpp.obj
C:/msys64/home/think/zyn-fusion-build/zynaddsubfx/src/Params/FilterParams.cpp: In lambda function:
C:/msys64/home/think/zyn-fusion-build/zynaddsubfx/src/Params/FilterParams.cpp:62:19: warning: macro expands to multiple statements [-Wmultistatement-macros]
   62 | #define rChangeCb obj->changed = true; if ( obj->time) {      \
      |                   ^~~
C:/msys64/home/think/zyn-fusion-build/zynaddsubfx/src/Params/FilterParams.cpp:157:17: note: in expansion of macro 'rChangeCb'
  157 |                 rChangeCb;
      |                 ^~~~~~~~~
C:/msys64/home/think/zyn-fusion-build/zynaddsubfx/src/Params/FilterParams.cpp:156:13: note: some parts of macro expansion are not guarded by this 'if' clause
  156 |             if(rtosc_narguments(msg))
      |             ^~
C:/msys64/home/think/zyn-fusion-build/zynaddsubfx/src/Misc/MiddleWare.cpp: In function 'void zyn::preparePadSynth(std::string, zyn::PADnoteParameters*, rtosc::RtData&
)':
**C:/msys64/home/think/zyn-fusion-build/zynaddsubfx/src/Misc/MiddleWare.cpp:199:47: error: cannot convert 'zyn::preparePadSynth(std::string, zyn::PADnoteParameters*, rt
osc::RtData&)::<lambda(unsigned int, zyn::PADnoteParameters::Sample&)>' to 'zyn::PADnoteParameters::callback' {aka 'std::function<void(int, zyn::PADnoteParameters::Sa
mple&&)>'}**
  199 |                        }, []{return false;}, 1);
      |                                               ^
In file included from C:/msys64/home/think/zyn-fusion-build/zynaddsubfx/src/Misc/MiddleWare.cpp:44:
C:/msys64/home/think/zyn-fusion-build/zynaddsubfx/src/Params/PADnoteParameters.h:193:57: note:   initializing argument 1 of 'int zyn::PADnoteParameters::sampleGenerat
or(zyn::PADnoteParameters::callback, std::function<bool()>, unsigned int)'
  193 |         int sampleGenerator(PADnoteParameters::callback cb,
      |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
[ 84%] Building CXX object src/CMakeFiles/zynaddsubfx_core.dir/Params/PADnoteParameters.cpp.obj
make[2]: *** [src/CMakeFiles/zynaddsubfx_core.dir/build.make:525：src/CMakeFiles/zynaddsubfx_core.dir/Misc/MiddleWare.cpp.obj] error 1
make[2]: *** Waiting for unfinished tasks....
make[1]: *** [CMakeFiles/Makefile2:1354：src/CMakeFiles/zynaddsubfx_core.dir/all] error 2
make: *** [Makefile:149：all] error 2

This build script is so broken and needs to be fixed!

**Comment by 143mailliw** [comment]
Same issue building for Windows on Windows 10 and Ubuntu 20.04.

**Comment by fundamental** [comment]
Resolved
