### ISSUE TITLE
Plugin GUI blocks the main GUI thread

### ISSUE THREAD

**Issue by iurienistor** [zynaddsubfx/zyn-fusion-build#56]
Plugin GUI blocks the main GUI thread. The leveler from GUI plugin are moving, the GUI of the host (Ardour) is freezing. Tested in Ardour5 and 6, also in Zrythm too. See attached video. 
[samples1-2020-06-03_00.55.27.mkv.tar.gz](https://github.com/zynaddsubfx/zyn-fusion-build/files/4719900/samples1-2020-06-03_00.55.27.mkv.tar.gz)

The sound is reproduced OK.

**Comment by iurienistor** [comment]
I think this is not related directly to the plugin, I've observed this also with other plugins.

**Comment by fundamental** [comment]
Thanks for the confirmation.
