### ISSUE TITLE
Building for Windows

### ISSUE THREAD

**Issue by EvzenHuml** [zynaddsubfx/zyn-fusion-build#6]
Hello, 
I'm trying to bulid Zyn-fusion like a win-VST on Ubuntu 16.04 and 14.04 but I get this error:

`zlib-1.2.7.tar.gz                                            100%[=============================================================================================================================================>] 547,22K   593KB/s    za 0,9s    

2018-01-16 09:51:41 (593 KB/s) – „zlib-1.2.7.tar.gz“ uloženo [560351/560351]

tar: zlib-1.2.7: Funkce read selhala: je adresářem
tar: Páska na začátku, končím
tar: Error is not recoverable: exiting now
Building static library libz.a version 1.2.7 with x86_64-w64-mingw32-gcc.
Checking for off64_t... Yes.
Checking for fseeko... Yes.
Checking for strerror... Yes.
Checking for unistd.h... Yes.
Checking for stdarg.h... Yes.
Checking whether to use vs[n]printf() or s[n]printf()... using vs[n]printf().
Checking for vsnprintf() in stdio.h... Yes.
Checking for return value of vsnprintf()... Yes.
Checking for attribute(visibility) support... No.
./ztest30865: 1: ./ztest30865: MZ����@���: not found
./ztest30865: 2: ./ztest30865: Syntax error: word unexpected (expecting ")")
Looking for a four-byte integer type... Not found.
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1 -I. -c -o example.o test/example.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1   -c -o adler32.o adler32.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1   -c -o crc32.o crc32.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1   -c -o deflate.o deflate.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1   -c -o infback.o infback.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1   -c -o inffast.o inffast.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1   -c -o inflate.o inflate.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1   -c -o inftrees.o inftrees.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1   -c -o trees.o trees.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1   -c -o zutil.o zutil.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1   -c -o compress.o compress.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1   -c -o uncompr.o uncompr.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1   -c -o gzclose.o gzclose.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1   -c -o gzlib.o gzlib.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1   -c -o gzread.o gzread.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1   -c -o gzwrite.o gzwrite.c
ar rc libz.a adler32.o crc32.o deflate.o infback.o inffast.o inflate.o inftrees.o trees.o zutil.o compress.o uncompr.o gzclose.o gzlib.o gzread.o gzwrite.o 
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1 -o example example.o -L. libz.a
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1 -I. -c -o minigzip.o test/minigzip.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1 -o minigzip minigzip.o -L. libz.a
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1 -I. -D_FILE_OFFSET_BITS=64 -c -o example64.o test/example.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1 -o example64 example64.o -L. libz.a
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1 -I. -D_FILE_OFFSET_BITS=64 -c -o minigzip64.o test/minigzip.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1 -o minigzip64 minigzip64.o -L. libz.a
cp libz.a /home/nemesis/zyn-fusion-build/zlib-1.2.7/../pkg//lib
chmod 644 /home/nemesis/zyn-fusion-build/zlib-1.2.7/../pkg//lib/libz.a
cp zlib.3 /home/nemesis/zyn-fusion-build/zlib-1.2.7/../pkg//share/man/man3
chmod 644 /home/nemesis/zyn-fusion-build/zlib-1.2.7/../pkg//share/man/man3/zlib.3
cp zlib.pc /home/nemesis/zyn-fusion-build/zlib-1.2.7/../pkg//lib/pkgconfig
chmod 644 /home/nemesis/zyn-fusion-build/zlib-1.2.7/../pkg//lib/pkgconfig/zlib.pc
cp zlib.h zconf.h /home/nemesis/zyn-fusion-build/zlib-1.2.7/../pkg//include
chmod 644 /home/nemesis/zyn-fusion-build/zlib-1.2.7/../pkg//include/zlib.h /home/nemesis/zyn-fusion-build/zlib-1.2.7/../pkg//include/zconf.h
cp ./libwinpthread* ./pkg/bin/
cp: nelze získat informace o './libwinpthread*': Adresář nebo soubor neexistuje
ERROR: 'cp ./libwinpthread* ./pkg/bin/' failed
`
Building for Linux works very well...

**Comment by fundamental** [comment]
The error sounds like there is something wrong with the zlib tar download. You might want to see what's wrong with the archive as it might be an issue like a regional mirror which doesn't affect the build when I run it.

**Comment by EvzenHuml** [comment]
I tried download https://www.zlib.net/fossils/zlib-1.2.7.tar.gz but the same error... with 1.2.6 too... there have to be something wrong...

**Comment by fundamental** [comment]
On the off chance that these are not the same file:

$ md5sum zlib-1.2.7.tar.gz
60df6a37c56e7c1366cca812414f7b85  zlib-1.2.7.tar.gz

**Comment by EvzenHuml** [comment]
md5sum zlib-1.2.7.tar.gz 
60df6a37c56e7c1366cca812414f7b85  zlib-1.2.7.tar.gz

**Comment by EvzenHuml** [comment]
on clean ubuntu-16.04.3-desktop-amd64 in virtualbox the same error...

**Comment by fundamental** [comment]
change this line https://github.com/zynaddsubfx/zyn-fusion-build/blob/master/z/build-zlib.sh#L3 to be the full name of the .tar.gz file and that should resolve the issue.

**Comment by EvzenHuml** [comment]
no luck... problem is maybe with the CC=x86_64-w64-mingw32-gcc
```
CC=x86_64-w64-mingw32-gcc ./configure --prefix=`pwd`/../pkg/ --static
Building static library libz.a version 1.2.7 with x86_64-w64-mingw32-gcc.
Checking for off64_t... Yes.
Checking for fseeko... Yes.
Checking for strerror... Yes.
Checking for unistd.h... Yes.
Checking for stdarg.h... Yes.
Checking whether to use vs[n]printf() or s[n]printf()... using vs[n]printf().
Checking for vsnprintf() in stdio.h... Yes.
Checking for return value of vsnprintf()... Yes.
Checking for attribute(visibility) support... No.
./ztest8764: 1: ./ztest8764: MZ����@���: not found
./ztest8764: 2: ./ztest8764: Syntax error: word unexpected (expecting ")")
Looking for a four-byte integer type... Not found.
```
without:
```
./configure --prefix=`pwd`/../pkg/ --static
Checking for gcc...
Building static library libz.a version 1.2.7 with gcc.
Checking for off64_t... Yes.
Checking for fseeko... Yes.
Checking for strerror... Yes.
Checking for unistd.h... Yes.
Checking for stdarg.h... Yes.
Checking whether to use vs[n]printf() or s[n]printf()... using vs[n]printf().
Checking for vsnprintf() in stdio.h... Yes.
Checking for return value of vsnprintf()... Yes.
Checking for attribute(visibility) support... Yes.
Looking for a four-byte integer type... Found.

```

**Comment by fundamental** [comment]
Is that a fatal error? it looks like the process continues after the ztest8764 hiccup. 

For reference the ubuntu VM version is 16.04 and the mingw version is 5.3.1 20160211.
Thanks for bearing with the scripts so far.

**Comment by EvzenHuml** [comment]
clean ubuntu 16.04 and g++-mingw-w64-x86-64 version (5.3.1-8ubuntu3+17)

`
`Checking for attribute(visibility) support... No.
./ztest32351: 1: ./ztest32351: MZ����@���: not found
./ztest32351: 7: ./ztest32351: Syntax error: "(" unexpected
Looking for a four-byte integer type... Not found.
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1 -I. -c -o example.o test/example.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1   -c -o adler32.o adler32.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1   -c -o crc32.o crc32.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1   -c -o deflate.o deflate.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1   -c -o infback.o infback.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1   -c -o inffast.o inffast.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1   -c -o inflate.o inflate.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1   -c -o inftrees.o inftrees.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1   -c -o trees.o trees.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1   -c -o zutil.o zutil.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1   -c -o compress.o compress.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1   -c -o uncompr.o uncompr.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1   -c -o gzclose.o gzclose.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1   -c -o gzlib.o gzlib.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1   -c -o gzread.o gzread.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1   -c -o gzwrite.o gzwrite.c
ar rc libz.a adler32.o crc32.o deflate.o infback.o inffast.o inflate.o inftrees.o trees.o zutil.o compress.o uncompr.o gzclose.o gzlib.o gzread.o gzwrite.o 
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1 -o example example.o -L. libz.a
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1 -I. -c -o minigzip.o test/minigzip.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1 -o minigzip minigzip.o -L. libz.a
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1 -I. -D_FILE_OFFSET_BITS=64 -c -o example64.o test/example.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1 -o example64 example64.o -L. libz.a
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1 -I. -D_FILE_OFFSET_BITS=64 -c -o minigzip64.o test/minigzip.c
x86_64-w64-mingw32-gcc -O3  -D_LARGEFILE64_SOURCE=1 -o minigzip64 minigzip64.o -L. libz.a
cp libz.a /home/nemesis/zyn-fusion-build-master/zlib-1.2.7/../pkg//lib
chmod 644 /home/nemesis/zyn-fusion-build-master/zlib-1.2.7/../pkg//lib/libz.a
cp zlib.3 /home/nemesis/zyn-fusion-build-master/zlib-1.2.7/../pkg//share/man/man3
chmod 644 /home/nemesis/zyn-fusion-build-master/zlib-1.2.7/../pkg//share/man/man3/zlib.3
cp zlib.pc /home/nemesis/zyn-fusion-build-master/zlib-1.2.7/../pkg//lib/pkgconfig
chmod 644 /home/nemesis/zyn-fusion-build-master/zlib-1.2.7/../pkg//lib/pkgconfig/zlib.pc
cp zlib.h zconf.h /home/nemesis/zyn-fusion-build-master/zlib-1.2.7/../pkg//include
chmod 644 /home/nemesis/zyn-fusion-build-master/zlib-1.2.7/../pkg//include/zlib.h /home/nemesis/zyn-fusion-build-master/zlib-1.2.7/../pkg//include/zconf.h
cp ./libwinpthread* ./pkg/bin/
cp: cannot stat './libwinpthread*': No such file or directory
ERROR: 'cp ./libwinpthread* ./pkg/bin/' failed
`
`

**Comment by fundamental** [comment]
https://github.com/zynaddsubfx/zyn-fusion-build/blob/master/build-windows.rb#L49 is the current error, not libz. I can't recall off the top of my head where I had gotten the libwinpthread dll from, but if you grab it from the most recent zyn-fusion demo package, then place it in the zyn-fusion-build directory, then that should move the process along.

Next time I have the VM running I'll have to see if I can recall how I originally downloaded it.

**Comment by EvzenHuml** [comment]
You are right. So I moved to the next step:

`-- Rtosc Build Configuration
-- =========================
-- 
-- PkgConfig disabled -- package NOT found
-- Liblo disabled     -- package NOT found
-- JACK disabled      -- package NOT found
-- NTK disabled       -- package NOT found
-- Perf Test(s) disabled
-- FLTK disabled      -- package NOT found
-- Checking Include Path
-- Checking Library Path
-- Could NOT find OSS (missing: OSS_INCLUDE_DIR) 
-- ALSA not found
-- Could NOT find FLTK (missing: FLTK_LIBRARIES FLTK_INCLUDE_DIR FLTK_FLUID_EXECUTABLE) 
-- Could NOT find CxxTest (missing: CXXTEST_INCLUDE_DIR CXXTEST_PYTHON_TESTGEN_EXECUTABLE) 
CMake Error at rtosc/cmake/ColorMessage.cmake:53 (_message):
  Could NOT find FFTW (missing: FFTW_LIBRARIES) 
Call Stack (most recent call first):
  /usr/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message)
  /usr/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindFFTW.cmake:16 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/CMakeLists.txt:45 (find_package)
`

**Comment by EvzenHuml** [comment]
Maybe It will be good write some How-to like build Windows VST...

**Comment by fundamental** [comment]
Yeah, since the windows build has always been on a single VM it's a fair bit more fragile than the linux build (used on 3 separate machines during dev time), but after this thread gets one successful build then it should be possible to have a simple how-to as well as a bunch of fixes to the build scripts themselves.

See https://github.com/zynaddsubfx/zyn-fusion-build/blob/master/z/windows-build.cmake#L7 for the next mistake of mine. Change /home/vm/argh/zyn-fusion-build/pkg to the right directory on your system (it looks like /home/nemesis/zyn-fusion-build-master/pkg based upon earlier posts) and things should proceed to the next step.

**Comment by Umcaruje** [comment]
Have the same issue, I switched the toolchain file to the correct directory on my system but cmake still fails to locate `pkgconfig`

**Comment by fundamental** [comment]
@Umcaruje it should be fine if pkg-config isn't found. All of the required dependencies should be found without it:
https://github.com/zynaddsubfx/zynaddsubfx/blob/master/src/CMakeLists.txt#L6-L49

If required dependencies like FFTW aren't found then that's a problem.

**Comment by fundamental** [comment]
in the case that other required deps are not found then double check their build shell scripts for excess wildcards.

**Comment by EvzenHuml** [comment]
Ok, next step:

[ 42%] Building CXX object src/CMakeFiles/zynaddsubfx_core.dir/version.cpp.obj
In file included from /usr/lib/gcc/x86_64-w64-mingw32/6.3-win32/include/c++/cwchar:44:0,
                 from /usr/lib/gcc/x86_64-w64-mingw32/6.3-win32/include/c++/bits/postypes.h:40,
                 from /usr/lib/gcc/x86_64-w64-mingw32/6.3-win32/include/c++/iosfwd:40,
                 from /usr/lib/gcc/x86_64-w64-mingw32/6.3-win32/include/c++/ios:38,
                 from /usr/lib/gcc/x86_64-w64-mingw32/6.3-win32/include/c++/ostream:38,
                 from /usr/lib/gcc/x86_64-w64-mingw32/6.3-win32/include/c++/iostream:39,
                 from /home/nemesis/zyn-fusion-build-master/zynaddsubfx/src/version.cpp:14:
/usr/include/wchar.h:27:36: fatal error: bits/libc-header-start.h: Adresář nebo soubor neexistuje
 #include <bits/libc-header-start.h>
                                    ^
compilation terminated.
src/CMakeFiles/zynaddsubfx_core.dir/build.make:63: návod pro cíl „src/CMakeFiles/zynaddsubfx_core.dir/version.cpp.obj“ selhal
make[2]: *** [src/CMakeFiles/zynaddsubfx_core.dir/version.cpp.obj] Chyba 1
CMakeFiles/Makefile2:1459: návod pro cíl „src/CMakeFiles/zynaddsubfx_core.dir/all“ selhal
make[1]: *** [src/CMakeFiles/zynaddsubfx_core.dir/all] Chyba 2
Makefile:140: návod pro cíl „all“ selhal
make: *** [all] Chyba 2
ERROR: 'make' failed

**Comment by fundamental** [comment]
I'm guessing that there's a missing dependency, though it does look like both of us are using a different mingw version. I'll have to check with my VM later today to see if I can get apt to tell me which package the header is located in on my system.

**Comment by fundamental** [comment]
Checking my VM it's showing mingw 5.3 and it does not have the bits/libc-header-start.h header and that header is not referred to by the cwchar header.

**Comment by EvzenHuml** [comment]
/usr/bin/x86_64-w64-mingw32-gcc -mstackrealign -shared -o libzest.dll -static-libgcc `find mruby/build/w64 -type f | grep -e "\.o$" | grep -v bin` \
        ./deps/libnanovg.a \
        src/osc-bridge/libosc-bridge.a \
        ./deps/libuv-v1.9.1/.libs/libuv.a \
        -lm -lpthread -lws2_32 -lkernel32 -lpsapi -luserenv -liphlpapi -lglu32 -lgdi32 -lopengl32
/usr/bin/x86_64-w64-mingw32-gcc -mstackrealign -DWIN32 test-libversion.c deps/pugl/build/libpugl-0.a -o zest.exe -lpthread -I deps/pugl -std=c99 -lws2_32 -lkernel32 -lpsapi -luserenv -liphlpapi -lglu32 -lgdi32 -lopengl32
Changing directory to ..
# Making a package in demo mode
pwd
/home/nemesis/zyn-fusion-build
rm    -rf w64-package
mkdir -p w64-package
mkdir -p w64-package/qml
touch    w64-package/qml/MainWindow.qml
mkdir -p w64-package/font
mkdir -p w64-package/schema
cp    mruby-zest-build/zest.exe         w64-package/zyn-fusion.exe
cp    mruby-zest-build/libzest.dll      w64-package/libzest.dll
cp    `find mruby-zest-build/deps/nanovg -type f | grep ttf$`                      w64-package/font/
cp    mruby-zest-build/src/osc-bridge/schema/test.json  w64-package/schema/
cp    build-zynaddsubfx-demo/src/Plugin/ZynAddSubFX/ZynAddSubFX.dll w64-package/
cp: cannot stat 'build-zynaddsubfx-demo/src/Plugin/ZynAddSubFX/ZynAddSubFX.dll': No such file or directory
ERROR: 'cp    build-zynaddsubfx-demo/src/Plugin/ZynAddSubFX/ZynAddSubFX.dll w64-package/' failed

**Comment by fundamental** [comment]
if ZynAddSubFX.dll cannot be copied then it has failed to build. You'll need to identify what's wrong with the C++ headers in your mingw install before that can happen. On the good side it looks like the GUI has compiled just fine.

**Comment by trayres** [comment]
As far as roadmap is concerned, CMAKE + MSYS2? That way we can do away with the VM for Windows builds. It looks like it would require quite a bit of work though.

**Comment by fundamental** [comment]
@trayes The build system/buildable systems depend upon the needs of users and contributors. At the moment (and historically) there aren't many people developing zyn on windows, so the mingw approach is being used to cross compile. Once the issues are sorted within this thread I'm going to want to add CI builds via travis-ci to ensure that the mingw build becomes easier to setup/use. IIRC travis-CI only has ubuntu and MacOS build machines.

If you're interested on doing development on a windows machine targeting a windows machine, then I would say that getting a msys build could be helpful, though it would certainly take a fair amount of time.

If you have a recent (windows 10 IIRC) windows install then one workaround before setting up anything native could be to use the linux subsystem for windows. I've been using that at my day job and have had decent success using it for my own work (though I haven't applied it to anything like zyn).

**Comment by trayres** [comment]
That's a good point, and would be a great use case for LSW, which I haven't tried yet.
I'll try to get cracking on it.

**Comment by RCJacH** [comment]
Tried building again with doxygen, fltk, and cxxtest installed and no luck.
How do I work with zyn in WSL? I rubied build-linux.sh and successfully installed. However I could find related documents on how alsa/jack works with WSL, or if it's possible to get any kind of graphic representation in WSL...

**Comment by fundamental** [comment]
> or if it's possible to get any kind of graphic representation in WSL

You'll need an X server to get a graphical representation.
I use 'XLaunch' and it has worked well enough for my uses on windows.

> how alsa/jack works with WSL

No idea. I haven't tried to output any audio from a WSL program. My guess is that ALSA works, but not particularly well.

> How do I work with zyn in WSL?

I would recommend trying to get the windows version built via the build-windows.rb script from within a WSL shell. If that's possible, then you get a native windows binary without the need for a Linux VM.

You should be able to run the Linux binary produced by the build-linux.rb, however I would expect that to not be the desired final result.

**Comment by RCJacH** [comment]
I got to 91% building in WSL after taking adviced from: https://www.kvraudio.com/forum/viewtopic.php?p=7030831#p7030831

Right now the error returns:

[ 91%] Linking CXX executable zynaddsubfx.exe
collect2: error: ld returned 1 exit status
src/CMakeFiles/zynaddsubfx.dir/build.make:107: recipe for target 'src/zynaddsubfx.exe' failed
make[2]: *** [src/zynaddsubfx.exe] Error 1
CMakeFiles/Makefile2:1533: recipe for target 'src/CMakeFiles/zynaddsubfx.dir/all' failed
make[1]: *** [src/CMakeFiles/zynaddsubfx.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
ERROR: 'make' failed

There's too many smaller error prior to this and I couldn't find anything related from a glance.
I'll try building on ubuntu later.

**Comment by fundamental** [comment]
> collect2: error: ld returned 1 exit status

A linker error indicates that some component at a previous stage failed to build. I'd recommend looking for an error earlier in the build process.

**Comment by bird0912** [comment]
Anyone had have succes building Zyn-fusion for windows? I really want to know how to build it

:) :3

**Comment by MatschbirneLive** [comment]
If you want, you can try the native windows build scripts for msys2's mingw64.exe

**Comment by bird0912** [comment]
But, what difference is with the .cmake based one

**Comment by bird0912** [comment]
How can I build it with the msys2 scripts?, sorry for my inexperience, I'm new

**Comment by MatschbirneLive** [comment]
No Problem, everybody has to start from somewhere :)
First download msys2 from here: https://www.msys2.org/

**Comment by defcronyke** [comment]
For some reason I had to launch the build script like this for it to work:
MSYSTEM="" sh build-mingw64.sh

Without erasing the $MSYSTEM value it would fail with this error:
No wscript file in directory C:/Users/person/Downloads/zyn-fusion-build/mruby-zest-build/deps/pugl

Even though the wscript file is there, I think there is some problem with parsing the path. I have python2.7 in my path if that matters.

**Comment by bird0912** [comment]
Thanks for the help, I will give it a try

**Comment by bird0912** [comment]
Thank you guys, It worked amazingly good. Thanks MatschbirneLive for your step by step manual. I only have one cuestion... can it be updated?

I can't thank you enough for your help. I'm pretty happy to have a powerful synth in my budget project.

:) :3

**Comment by MatschbirneLive** [comment]
What do you mean by updated ? 
If you mean the synth, the build script downloads the latest source code of zynaddsubfx from git, so to update you just simply need to rebuild zynfusion again.

**Comment by EvzenHuml** [comment]
This way (msys2) it works like a charm ;-) Thank you very much

**Comment by bird0912** [comment]
Thank you, you are the best :)

**Comment by Paternostro** [comment]
> 
> 
> No Problem, everybody has to start from somewhere :)
> First download msys2 from here: https://www.msys2.org/
> Then open the msys2 shell and type
> `pacman -Syu`
> If told to restart the shell and then type
> `pacman -Su`
> Now you just need git, to install just type:
> `pacman -S git`
> Now you can close the msys2 shell and now you have to open the mingw64.exe (Should be in the same directory as the shell)
> Now You need to type
> `git clone https://github.com/zynaddsubfx/zyn-fusion-build.git`
> `cd zyn*`
> `./build-mingw64.sh`
> Now the script should download all required packages and then build ZynFusion
> Hope it helps

Hello, 

I tried these steps and it failed. Because of a file called backtrace

 I then followed the steps from here:
https://github.com/zynaddsubfx/zyn-fusion-build/issues/33

That got me a bit further and then it failed because I didnt have python2 yet.
I installed python2 and that got me a bit further again. 

**But now I have a bunch of errors starting with:**
D:/Applications/zyn-fusion-build/mruby-zest-build/mruby/src/backtrace.c: In function 'print_backtrace_saved':
D:/Applications/zyn-fusion-build/mruby-zest-build/mruby/src/backtrace.c:122:23: error: 'mrb_state' {aka 'struct mrb_state'} has no member named 'backtrace'

**eventually resulting in:** 
rake aborted!
Command failed with status (1): [gcc -I/d/Applications/zyn-fusion-build/mru...]
/d/Applications/zyn-fusion-build/mruby-zest-build/mruby/lib/mruby/build/command.rb:31:in `_run'
/d/Applications/zyn-fusion-build/mruby-zest-build/mruby/lib/mruby/build/command.rb:36:in `rescue in _run'
/d/Applications/zyn-fusion-build/mruby-zest-build/mruby/lib/mruby/build/command.rb:32:in `_run'
/d/Applications/zyn-fusion-build/mruby-zest-build/mruby/lib/mruby/build/command.rb:89:in `run'
/d/Applications/zyn-fusion-build/mruby-zest-build/mruby/lib/mruby/build/command.rb:113:in `block (2 levels) in define_rules'

Caused by:
Command failed with status (1): [gcc -I/d/Applications/zyn-fusion-build/mru...]
/d/Applications/zyn-fusion-build/mruby-zest-build/mruby/lib/mruby/build/command.rb:33:in `_run'
/d/Applications/zyn-fusion-build/mruby-zest-build/mruby/lib/mruby/build/command.rb:89:in `run'
/d/Applications/zyn-fusion-build/mruby-zest-build/mruby/lib/mruby/build/command.rb:113:in `block (2 levels) in define_rules'
Tasks: TOP => default => all => /d/Applications/zyn-fusion-build/mruby-zest-build/mruby/build/host/lib/libmruby.flags.mak => /d/Applications/zyn-fusion-build/mruby-zest-build/mruby/build/host/lib/libmruby.a => /d/Applications/zyn-fusion-build/mruby-zest-build/mruby/build/host/src/backtrace.o
(See full trace by running task with --trace)
make: *** [Makefile:42: windows] Error 1


I've tried removing the print function because who needs printing in a finished product ;) but it didnt help.

Anyone has some ideas? I would love to use this as a 64-bit vst in Ableton Live ;)

Kind regards,

**Comment by deli73** [comment]
i've done a LOT of fiddling to get this far but the point i'm at now is: z/build-package.sh is failing on the Cmake call: 
> cmake ../zynaddsubfx/ -DCMAKE_TOOLCHAIN_FILE=../z/mingw64-build.cmake -DOssEnable=False -DGuiModule=zest -DDemoMode=$2 -DCMAKE_INSTALL_PREFIX=/usr -DDefaultOutput=pa

and it's not giving me any errors. it's just straight up freezing the whole msys2 terminal.

if i turn on a debug trace, it outputs *something*, but i can't see it all because the terminal freezes, and i can't get it to pipe log output to a file either, or rather i can but it stops before the error happens

outputs this and then stops:
> /home/deli/zyn-fusion-build-master/zyn-fusion-build/pkg/:/usr/local/bin:/usr/bin:/bin:/opt/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
> Running with trace output on.
> -- Found PkgConfig: /usr/bin/pkg-config.exe (found version "0.29.2")

**Comment by fundamental** [comment]
While this isn't an error that I've seen, you might want to see if a different version of cmake has different behavior.

**Comment by msebi** [comment]
> MSYSTEM="" sh build-mingw64.sh

Dude, I love you (no homo).

**Comment by defcronyke** [comment]
> > MSYSTEM="" sh build-mingw64.sh
> 
> Dude, I love you (no homo).

@msebi,

I don't remember how I figured that out or why it was necessary, but I'm glad it helped someone else also.
