### ISSUE TITLE
Wiki - Arch build detailed instructions: rake missing

### ISSUE THREAD

**Issue by mlapla** [zynaddsubfx/zyn-fusion-build#64]
Hi,

I builded the project on Arch (Manjaro gnome 20.1). On upon running ruby `build-linux.rb`, the build failed with the error message: `make clean failed`.

Upon installing the `ruby-rake` package, the build completed sucessfully.
Perhaps the detailed instructions for building on Arch be updated and include this dependency?

**Comment by fundamental** [comment]
I'm going to assume that `rake` aliases to `ruby-rake` since it looks like the docker version of the arch build I have setup installs `rake` via pacman. If that's the case the additional dep has been added to the wiki.
