### ISSUE TITLE
Linux cc build error

### ISSUE THREAD

**Issue by rajansaini691** [zynaddsubfx/zyn-fusion-build#70]
Getting the following error while building on Arch:
```
[ 37%] Building C object src/CMakeFiles/zynadds sf/tlsf.c.o
cc: error: unrecognized command-line option ‘--system-header-prefix=FL/’
```
I know that clang supports this option while gcc doesn't, but I'm not very familiar with the build system here. Any help would be appreciated!

**Comment by fundamental** [comment]
Is this building with the build scripts here or is this building from the zynaddsubfx repo itself?

I wouldn't expect anything related to FLTK given the options set in these build scripts, but it's possible something is leaking through.

**Comment by rajansaini691** [comment]
I think I used these build scripts; I ran `ruby build-linux.rb`. Do I need to install fltk?

**Comment by fundamental** [comment]
On 01-27, rajansaini691 wrote:
> I think I used these build scripts; I ran `ruby build-linux.rb`. Do I need to install fltk? 

You shouldn't need to. I'm mostly asking to verify system config for
when I try to replicate the issue within docker.
As long as I can replicate, then it should be possible to identify the
mistake in zyn's CMakeLists.txt file(s).

**Comment by fundamental** [comment]
I'd make sure your system is up to date, then make a new build folder, and hopefully the issue disappears. Using an arch docker (specifically https://github.com/zynaddsubfx/zyn-fusion-build/blob/master/linux-system-testers/arch-zynaddsubfx.dockerfile ) I can not replicate the issue. I see the line in our cmake files which was introducing the compiler argument, but it only gets included if the compiler passes a test indicating it's a usable flag. With all the runs I was able to make the compiler flag was detected as unusable in gcc and thus did not get used.

Let me know if you have a method for replicating, but if I can't repeat the situation within a constrained setup like docker I'm stumped.
