### ISSUE TITLE
Build fails on Linux with "make: *** No rule to make target 'setup'.  Stop." when running build-linux.rb

### ISSUE THREAD

**Issue by eventual-recluse** [zynaddsubfx/zyn-fusion-build#72]
While trying to build on Fedora 32, and following the instructions at the 'Building on Linux' page:

https://github.com/zynaddsubfx/zyn-fusion-build/wiki/Building-on-Linux

the build stopped with the following message when running  'ruby build-linux.rb' :

Getting Zest
Changing directory to mruby-zest-build
make setup
make: *** No rule to make target 'setup'.  Stop.
ERROR: 'make setup' failed

NOTE:
After editing the build script by commenting out      cmd   "make setup"      and        cmd   "make builddep"       in   def get_zest()
and replacing them with     cmd   "make deps/libuv.a"       the build seems to have completed successfully.

def get_zest()
    stage "Getting Zest"
    #Clone the unreleased UI submodules
    cmd   "git clone --depth=1 https://github.com/mruby-zest/mruby-zest-build"
    chdir "mruby-zest-build"
    cmd   "git submodule update --init"
    cmd   "ruby rebuild-fcache.rb"
    #cmd   "mv testing-cache.rb src/mruby-widget-lib/mrblib/fcache.rb"
    #cmd   "make setup"
    #cmd   "make builddep"
    cmd   "make deps/libuv.a"
    chdir ".."
end

**Comment by fundamental** [comment]
Thanks for the bug report. This is a result of me merging some work over in the mruby-zest-build repo without fixing up the build scripts here at the same time. I think just "make" (which is done in a later step) should work currently relying on the system libuv, but I may have missed something within the code review. I'll try to get to this with the next timeslot I have for some zyn hacking.

**Comment by eventual-recluse** [comment]
Thanks for the quick response! I did try just using "make" and the build completed, but Zyn-Fusion crashed when launching with this error:

./zyn-fusion: symbol lookup error: ./libzest.so: undefined symbol: uv_loop_init

Using  "make deps/libuv.a" worked, though.

**Comment by fundamental** [comment]
Interesting. I thought I had fixed that error a few hours ago with commit 2b399dfd6fded703ed7ef781d07b00529f057f7a in mruby-zest-build

**Comment by eventual-recluse** [comment]
You're right, your commit fixed it.

(I tried it again, this time only commenting out  cmd "make setup" and cmd "make builddep" in def get_zest(), without adding anything else. The build completed and it doesn't crash on launch now.)

**Comment by fundamental** [comment]
Should be resolved, though I updated scripts based upon this conversation rather than fully testing them post-modification. Let me know if there are still issues.
