### ISSUE TITLE
src/bridge.h:1:10: fatal error: uv.h: No such file or directory

### ISSUE THREAD

**Issue by krznv** [zynaddsubfx/zyn-fusion-build#74]
checking for sys/sysmacros.h... yes
configure: creating ./config.status
config.status: creating config.h
cd src/osc-bridge    && make lib
make[1]: Entering directory '/home/krznv/Downloads/git/zyn-fusion-build/mruby-zest-build/src/osc-bridge'
cc  -std=gnu99 -Wall -Wextra -I . -O3 -g -fPIC -c src/bridge.c src/cache.c src/parse-schema.c src/schema.c rtosc/rtosc.c
In file included from src/bridge.c:7:
src/bridge.h:1:10: fatal error: uv.h: No such file or directory
    1 | #include <uv.h>
      |          ^~~~~~
compilation terminated.
make[1]: *** [Makefile:13: lib] Error 1
make[1]: Leaving directory '/home/krznv/Downloads/git/zyn-fusion-build/mruby-zest-build/src/osc-bridge'
make: *** [Makefile:7: all] Error 2
ERROR: 'make' failed

**Comment by DavidRadberg** [comment]
I had the same issue.
Running
`sudo apt-get install -y libuv1-dev`
solved it for me.

**Comment by fundamental** [comment]
Dup of #73 and it looks like someone modified the wiki instructions updating the new dep.
