### ISSUE TITLE
Building tarball for Arch Linux results in ERROR: cmake failed

### ISSUE THREAD

**Issue by not-a-cube** [zynaddsubfx/zyn-fusion-build#76]
Building the zyn-fusion tarballs on Arch Linux gives the following error when building the demo tarball:
ERROR: 'cmake ../zynaddsubfx/ -DGuiModule=zest -DDemoMode=true -DCMAKE_INSTALL_PREFIX=/usr' failed

**Comment by fundamental** [comment]
Please clarify the commands used. There's a few different ways to build things and I've confirmed that the docker build on arch works fine which isn't to say that something else might be broken.

**Comment by not-a-cube** [comment]
I was referring to the build-linux.rb script.

**Comment by fundamental** [comment]
My money is on missing dependencies given it works in a dockerized arch setup. Can you provide information about the failure? 

I'm guessing the build script hides the output, but you should be able to see it via something along the lines of:

```
cd tmp
git clone https://github.com/zynaddsubfx/zynaddsubfx
cd zynaddsubfx
mkdir build
cd build
cmake .. -DGuiModule=zest -DDemoMode=true
```

**Comment by not-a-cube** [comment]
I think you are right. I tried it, and it works fine now. Sorry if this felt like a waste of time, this was my first issue on GitHub.

**Comment by fundamental** [comment]
No problem at all. These sorts of things happen all the time. I'm guessing if I responded earlier there was a bug which got fixed elsewhere. Thanks for the report :+1:
