### ISSUE TITLE
build-linux.rb on Kubuntu 20.04 fails when installing the built package

### ISSUE THREAD

**Issue by martinvlk** [zynaddsubfx/zyn-fusion-build#77]
```
-- Installing: /usr/lib/lv2/ZynAddSubFX.lv2presets
CMake Error at cmake_install.cmake:74 (file):
  file INSTALL cannot make directory "/usr/lib/lv2/ZynAddSubFX.lv2presets":
  Too many levels of symbolic links.


make: *** [Makefile:86: install] Chyba 1
ERROR: 'sudo make install' failed
```

**Comment by martinvlk** [comment]
Looks like a symbolic link pointing to itself or the link that points to another one that points to itself...

**Comment by fundamental** [comment]
The symbolic links created by the build scripts should result in them going from the lv2 path into /opt. I suspect that this is an issue with a pre-existing broken symbolic link.

**Comment by martinvlk** [comment]
Correct, after clearing it up, I get further error:
```
-- Installing: /usr/lib/lv2/ZynAddSubFX.lv2presets
CMake Error at cmake_install.cmake:74 (file):
  file INSTALL cannot make directory "/usr/lib/lv2/ZynAddSubFX.lv2presets":
  No such file or directory.


make: *** [Makefile:86: install] Chyba 1
ERROR: 'sudo make install' failed
```

**Comment by fundamental** [comment]
Something is very strange on your system. "sudo make install" has permissions as the root user to make the directory. It should not have a failure mode.

**Comment by martinvlk** [comment]
In the end I managed to successfully build the package, after several attempts. It required me to manually clean up dangling symbolic link files. Any chance the script handles this automatically?

**Comment by fundamental** [comment]
On 05-11, Martin Vlk wrote:
> In the end I managed to successfully build the package, after several attempts. It required me to manually clean up dangling symbolic link files. Any chance the script handles this automatically?

Strange. I have not seen such symbolic link issues myself. The scripts
should handle things automatically from a clean or moderately dirty
system state.

**Comment by martinvlk** [comment]
Ah well, I'll close that for now. Thank You.
