### ISSUE TITLE
build-windows.rb creates ZynAddSubFX.dll.   Needed to be renamed to Zyn.AddSubFX.vst3 to be found in Reaper 6.29

### ISSUE THREAD

**Issue by Schmitty2005** [zynaddsubfx/zyn-fusion-build#82]
DLL file built with **build-windows.rb** on Ubuntu 20.04.  ZynAddSubFX.dll worked in Element [https://kushview.net/element/](url)

Needed to be renamed to  Zyn.AddSubFX.vst3 to be found in Reaper 6.29.  Worked after renamed.

According to this article at  Steinberg,  [https://helpcenter.steinberg.de/hc/en-us/articles/115000177084-VST-plug-in-locations-on-Windows](url), VST3's have a .vst3 extension while VST2's have .dll extension.

Could this simply be in the notes at the end of the **build-windows.rb** or should **build-windows.rb** rename ZynAddSubFX.dll to ZynAddSubFX.vst3 ?

**Comment by fundamental** [comment]
Zyn does not build a VST3 plugin, it builds a VST2 one, so by your description it would be incorrect to move the shared lib.

**Comment by Schmitty2005** [comment]
Thank you for the explanation.  I did not know it was possible to still build VST2's.  I was remembering the Steinberg VST2 SDK being closed source.  I assumed all open source projects were now using VST3 SDK.

**Comment by fundamental** [comment]
Open source projects can rely on a reverse engineered header. Anyone using said header has not formed any agreement with Steinberg.
