### ISSUE TITLE
building zynaddsubfx fails: ADnoteUI.cxx: No such file

### ISSUE THREAD

**Issue by grammoboy2** [zynaddsubfx/zyn-fusion-build#85]
git clone https://github.com/zynaddsubfx/zynaddsubfx.git
cd zynaddsubfx
mkdir build
cd build
cmake ..
make

Scanning dependencies of target zynaddsubfx_gui
[ 54%] Generating ADnoteUI.cxx
[ 55%] Building CXX object src/UI/CMakeFiles/zynaddsubfx_gui.dir/ADnoteUI.cxx.o
c++: error: /home/debian/develop/zynaddsubfx/build/src/UI/ADnoteUI.cxx: No such file or directory
c++: fatal error: no input files
compilation terminated.
make[2]: *** [src/UI/CMakeFiles/zynaddsubfx_gui.dir/build.make:178: src/UI/CMakeFiles/zynaddsubfx_gui.dir/ADnoteUI.cxx.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2465: src/UI/CMakeFiles/zynaddsubfx_gui.dir/all] Error 2
make: *** [Makefile:160: all] Error 2

**Comment by fundamental** [comment]
Classic symptoms of fltk being installed without 'fluid' being installed. After all these years I still have no clue why debian/ubuntu broke those two into separate packages. If this isn't the problem let me know and I'll reopen.
