### ISSUE TITLE
Wrong path in Makefile.windows.mk

### ISSUE THREAD

**Issue by pfranta6** [zynaddsubfx/zyn-fusion-build#89]
Make for  Windows in Linux environment end with error, that it can not find the ZynAddSubFX.dll. The problem is there:

cp $(ZYNADDSUBFX_BUILD_DIR)/src/Plugin/ZynAddSubFX/ZynAddSubFX.dll $(ZYN_FUSION_OUT)/

Right path should be look like it:

cp $(ZYNADDSUBFX_BUILD_DIR)/src/Plugin/ZynAddSubFX/vst/ZynAddSubFX.dll $(ZYN_FUSION_OUT)/

Then a make finished successfully.

**Comment by fundamental** [comment]
Likely a consequence of https://github.com/zynaddsubfx/zynaddsubfx/pull/151 . As you've mentioned it's a 4 character fix, so feel free to add a PR if you want to have the fix recorded in git history or I'll fix it in one of the periodic git issues sweeps and credit you for the find :)
