### ISSUE TITLE
zyn-fusion installation fails - Manjaro XFCE 

### ISSUE THREAD

**Issue by kx05ymu** [zynaddsubfx/zyn-fusion-build#94]
Hi - I've been following the Unfar Youtube Audio for Manjaro instructional, and trying to install zyn-fusion threw up failed on a make error. The output from the full install is below.

[steve@steve-10rs003ruk ~]$ /bin/bash -c "yay --noconfirm  --noeditmenu  -S --aur zyn-fusion;echo 'Press any key to continue...'"
:: Checking for conflicts...
:: Checking for inner conflicts...
[Repo:1]  mxml-3.3-1
[Repo Make:5]  jsoncpp-1.9.5-1  rhash-1.4.2-1  cmake-3.22.1-5  ruby-rake-13.0.6-1  python2-2.7.18-5
[Aur:1]  zyn-fusion-3.0.5-4

:: (1/1) Downloaded PKGBUILD: zyn-fusion
  1 zyn-fusion                               (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: (1/1) Parsing SRCINFO: zyn-fusion
[sudo] password for steve: 
resolving dependencies...
looking for conflicting packages...

Packages (6) cmake-3.22.1-5  jsoncpp-1.9.5-1  mxml-3.3-1  python2-2.7.18-5  rhash-1.4.2-1  ruby-rake-13.0.6-1

Total Download Size:    24.50 MiB
Total Installed Size:  141.93 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 python2-2.7.18-5-x86_64                                                              13.6 MiB  5.94 MiB/s 00:02 [###################################################################] 100%
 cmake-3.22.1-5-x86_64                                                                 9.9 MiB  6.25 MiB/s 00:02 [###################################################################] 100%
 mxml-3.3-1-x86_64                                                                   705.2 KiB  5.42 MiB/s 00:00 [###################################################################] 100%
 rhash-1.4.2-1-x86_64                                                                164.8 KiB  4.88 MiB/s 00:00 [###################################################################] 100%
 jsoncpp-1.9.5-1-x86_64                                                               94.1 KiB  4.59 MiB/s 00:00 [###################################################################] 100%
 ruby-rake-13.0.6-1-any                                                               75.0 KiB  1745 KiB/s 00:00 [###################################################################] 100%
 Total (6/6)                                                                          24.5 MiB  5.86 MiB/s 00:04 [###################################################################] 100%
(6/6) checking keys in keyring                                                                                   [###################################################################] 100%
(6/6) checking package integrity                                                                                 [###################################################################] 100%
(6/6) loading package files                                                                                      [###################################################################] 100%
(6/6) checking for file conflicts                                                                                [###################################################################] 100%
(6/6) checking available disk space                                                                              [###################################################################] 100%
:: Processing package changes...
(1/6) installing mxml                                                                                            [###################################################################] 100%
(2/6) installing jsoncpp                                                                                         [###################################################################] 100%
Optional dependencies for jsoncpp
    jsoncpp-doc: documentation
(3/6) installing rhash                                                                                           [###################################################################] 100%
(4/6) installing cmake                                                                                           [###################################################################] 100%
Optional dependencies for cmake
    qt6-base: cmake-gui [installed]
(5/6) installing ruby-rake                                                                                       [###################################################################] 100%
(6/6) installing python2                                                                                         [###################################################################] 100%
Optional dependencies for python2
    tk: for IDLE
    python2-setuptools
    python2-pip
:: Running post-transaction hooks...
(1/4) Arming ConditionNeedsUpdate...
(2/4) Updating the MIME type database...
(3/4) Updating icon theme caches...
(4/4) Updating the desktop file MIME type cache...
==> Making package: zyn-fusion 3.0.5-4 (Mon 03 Jan 2022 10:10:33 GMT)
==> Retrieving sources...
  -> Cloning zynaddsubfx git repo...
Cloning into bare repository '/home/steve/.cache/yay/zyn-fusion/zynaddsubfx'...
remote: Enumerating objects: 25510, done.
remote: Counting objects: 100% (1750/1750), done.
remote: Compressing objects: 100% (612/612), done.
remote: Total 25510 (delta 1299), reused 1507 (delta 1132), pack-reused 23760
Receiving objects: 100% (25510/25510), 10.88 MiB | 5.25 MiB/s, done.
Resolving deltas: 100% (20553/20553), done.
  -> Cloning mruby-zest-build git repo...
Cloning into bare repository '/home/steve/.cache/yay/zyn-fusion/mruby-zest-build'...
remote: Enumerating objects: 2808, done.
remote: Counting objects: 100% (953/953), done.
remote: Compressing objects: 100% (606/606), done.
remote: Total 2808 (delta 593), reused 601 (delta 344), pack-reused 1855
Receiving objects: 100% (2808/2808), 772.50 KiB | 5.02 MiB/s, done.
Resolving deltas: 100% (1706/1706), done.
  -> Found BashCompletion.cmake
  -> Found gcc10.patch
  -> Found file-picker.patch
  -> Found mruby.patch
  -> Found mruby-dir-glob.patch
  -> Found parameter-ranges.patch
==> Validating source files with b2sums...
    zynaddsubfx ... Skipped
    mruby-zest-build ... Skipped
    BashCompletion.cmake ... Passed
    gcc10.patch ... Passed
    file-picker.patch ... Passed
    mruby.patch ... Passed
    mruby-dir-glob.patch ... Passed
    parameter-ranges.patch ... Passed
 -> mxml not satisfied, flushing install queue
==> Making package: zyn-fusion 3.0.5-4 (Mon 03 Jan 2022 10:10:39 GMT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating zynaddsubfx git repo...
Fetching origin
  -> Updating mruby-zest-build git repo...
Fetching origin
  -> Found BashCompletion.cmake
  -> Found gcc10.patch
  -> Found file-picker.patch
  -> Found mruby.patch
  -> Found mruby-dir-glob.patch
  -> Found parameter-ranges.patch
==> Validating source files with b2sums...
    zynaddsubfx ... Skipped
    mruby-zest-build ... Skipped
    BashCompletion.cmake ... Passed
    gcc10.patch ... Passed
    file-picker.patch ... Passed
    mruby.patch ... Passed
    mruby-dir-glob.patch ... Passed
    parameter-ranges.patch ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of zynaddsubfx git repo...
Cloning into 'zynaddsubfx'...
done.
Switched to a new branch 'makepkg'
  -> Creating working copy of mruby-zest-build git repo...
Cloning into 'mruby-zest-build'...
done.
Switched to a new branch 'makepkg'
==> Starting prepare()...
Submodule 'DPF' (https://github.com/DISTRHO/DPF) registered for path 'DPF'
Submodule 'instruments' (https://github.com/zynaddsubfx/instruments) registered for path 'instruments'
Submodule 'rtosc' (https://github.com/fundamental/rtosc) registered for path 'rtosc'
Cloning into '/home/steve/.cache/yay/zyn-fusion/src/zynaddsubfx/DPF'...
Cloning into '/home/steve/.cache/yay/zyn-fusion/src/zynaddsubfx/instruments'...
fatal: unable to access 'https://github.com/zynaddsubfx/instruments/': Could not resolve host: github.com
fatal: clone of 'https://github.com/zynaddsubfx/instruments' into submodule path '/home/steve/.cache/yay/zyn-fusion/src/zynaddsubfx/instruments' failed
Failed to clone 'instruments'. Retry scheduled
Cloning into '/home/steve/.cache/yay/zyn-fusion/src/zynaddsubfx/rtosc'...
Cloning into '/home/steve/.cache/yay/zyn-fusion/src/zynaddsubfx/instruments'...
Submodule path 'DPF': checked out 'e0d8e14a14d407648768da7e34bcf31812245387'
Submodule path 'instruments': checked out '22ea12d55e985eee6b57fcac1cafb7df6ae392f2'
Submodule path 'rtosc': checked out 'c4f131c96e95d23ecbfbc5f1794c5d349ca564c9'
Submodule path 'instruments': checked out '22ea12d55e985eee6b57fcac1cafb7df6ae392f2'
Applied patch to 'src/Misc/MiddleWare.cpp' cleanly.
Applied patch to 'src/Effects/Effect.h' cleanly.
Submodule 'deps/mruby-complex' (https://github.com/pbosetti/mruby-complex) registered for path 'deps/mruby-complex'
Submodule 'deps/mruby-dir-glob' (https://github.com/gromnitsky/mruby-dir-glob) registered for path 'deps/mruby-dir-glob'
Submodule 'deps/mruby-glew' (https://github.com/IceDragon200/mruby-glew) registered for path 'deps/mruby-glew'
Submodule 'deps/mruby-glfw3' (https://github.com/IceDragon200/mruby-glfw3) registered for path 'deps/mruby-glfw3'
Submodule 'deps/mruby-io' (https://github.com/iij/mruby-io) registered for path 'deps/mruby-io'
Submodule 'deps/mruby-nanovg' (https://github.com/mruby-zest/mruby-nanovg) registered for path 'deps/mruby-nanovg'
Submodule 'deps/mruby-regexp-pcre' (https://github.com/iij/mruby-regexp-pcre) registered for path 'deps/mruby-regexp-pcre'
Submodule 'deps/mruby-set' (https://github.com/yui-knk/mruby-set) registered for path 'deps/mruby-set'
Submodule 'deps/mruby-sleep' (https://github.com/matsumoto-r/mruby-sleep) registered for path 'deps/mruby-sleep'
Submodule 'deps/nanovg' (https://github.com/memononen/nanovg) registered for path 'deps/nanovg'
Submodule 'deps/pugl' (https://github.com/mruby-zest/pugl.git) registered for path 'deps/pugl'
Submodule 'deps/rtosc' (https://github.com/fundamental/rtosc) registered for path 'deps/rtosc'
Submodule 'mruby' (https://github.com/mruby/mruby) registered for path 'mruby'
Submodule 'src/mruby-qml-parse' (https://github.com/mruby-zest/mruby-qml-parse) registered for path 'src/mruby-qml-parse'
Submodule 'src/mruby-qml-spawn' (https://github.com/mruby-zest/mruby-qml-spawn) registered for path 'src/mruby-qml-spawn'
Submodule 'src/mruby-zest' (https://github.com/mruby-zest/mruby-zest) registered for path 'src/mruby-zest'
Submodule 'deps/osc-bridge' (https://github.com/mruby-zest/osc-bridge) registered for path 'src/osc-bridge'
Cloning into '/home/steve/.cache/yay/zyn-fusion/src/mruby-zest-build/deps/mruby-complex'...
Cloning into '/home/steve/.cache/yay/zyn-fusion/src/mruby-zest-build/deps/mruby-dir-glob'...
Cloning into '/home/steve/.cache/yay/zyn-fusion/src/mruby-zest-build/deps/mruby-glew'...
Cloning into '/home/steve/.cache/yay/zyn-fusion/src/mruby-zest-build/deps/mruby-glfw3'...
Cloning into '/home/steve/.cache/yay/zyn-fusion/src/mruby-zest-build/deps/mruby-io'...
Cloning into '/home/steve/.cache/yay/zyn-fusion/src/mruby-zest-build/deps/mruby-nanovg'...
Cloning into '/home/steve/.cache/yay/zyn-fusion/src/mruby-zest-build/deps/mruby-regexp-pcre'...
Cloning into '/home/steve/.cache/yay/zyn-fusion/src/mruby-zest-build/deps/mruby-set'...
Cloning into '/home/steve/.cache/yay/zyn-fusion/src/mruby-zest-build/deps/mruby-sleep'...
Cloning into '/home/steve/.cache/yay/zyn-fusion/src/mruby-zest-build/deps/nanovg'...
Cloning into '/home/steve/.cache/yay/zyn-fusion/src/mruby-zest-build/deps/pugl'...
Cloning into '/home/steve/.cache/yay/zyn-fusion/src/mruby-zest-build/deps/rtosc'...
Cloning into '/home/steve/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby'...
Cloning into '/home/steve/.cache/yay/zyn-fusion/src/mruby-zest-build/src/mruby-qml-parse'...
Cloning into '/home/steve/.cache/yay/zyn-fusion/src/mruby-zest-build/src/mruby-qml-spawn'...
Cloning into '/home/steve/.cache/yay/zyn-fusion/src/mruby-zest-build/src/mruby-zest'...
Cloning into '/home/steve/.cache/yay/zyn-fusion/src/mruby-zest-build/src/osc-bridge'...
Submodule path 'deps/mruby-complex': checked out '4f57a1ef9f968e9d5eef53667c7960a2e98c9750'
Submodule path 'deps/mruby-dir-glob': checked out '334c040a2e2c4c2689f8c3440168011f64d57ada'
Submodule path 'deps/mruby-glew': checked out '6849202f885516b381406e799dcdb430065e19cf'
Submodule path 'deps/mruby-glfw3': checked out '0eeee012fd4bbd6544dd34f17ce2b476ad71d86b'
Submodule path 'deps/mruby-io': checked out '1c4428880b2f0f0fcd81ea2debc5f4459a7ed53c'
Submodule path 'deps/mruby-nanovg': checked out 'd7d4e1ce434131babb5fd6026201011f5b0b50ea'
Submodule path 'deps/mruby-regexp-pcre': checked out 'cd13fb15fd6b813fc6c9bc2f17db20257f71bb0c'
Submodule path 'deps/mruby-set': checked out '68334311ac7386eef84f3034a256e7135a87625d'
Submodule path 'deps/mruby-sleep': checked out '263d70351a4f75a875f2a35ab9a9128d1ef5da90'
Submodule path 'deps/nanovg': checked out 'b83cf926525e7cea8d2483da2a75852b8c7b6d28'
Submodule path 'deps/pugl': checked out 'd87062625ed652df9455bd6f60ea89c53515c43a'
Submodule path 'deps/rtosc': checked out '70307782622c668a325992f6887f354ca30d5e14'
Submodule path 'mruby': checked out 'e5b61d34f65cabfbe88f3f1709a1f9cff86585de'
Submodule path 'src/mruby-qml-parse': checked out 'a3e687124b5afe51cdc4d8d36cbff7204e81a1b4'
Submodule path 'src/mruby-qml-spawn': checked out '77f782643c78a9cfe48e49f027d9978fb5e27d77'
Submodule path 'src/mruby-zest': checked out '8352b7ae4a0efba111f72572d993efb892a27761'
Submodule path 'src/osc-bridge': checked out '67b0b5c85e0072ea0bee1129a1ec8cef1328faaa'
Applied patch to 'src/mruby-widget-lib/src/gem.c' cleanly.
~/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby ~/.cache/yay/zyn-fusion/src/mruby-zest-build
Applied patch to 'Rakefile' cleanly.
~/.cache/yay/zyn-fusion/src/mruby-zest-build
~/.cache/yay/zyn-fusion/src/mruby-zest-build/deps/mruby-dir-glob ~/.cache/yay/zyn-fusion/src/mruby-zest-build
Applied patch to 'mrbgem.rake' cleanly.
~/.cache/yay/zyn-fusion/src/mruby-zest-build
/home/steve/.cache/yay/zyn-fusion/PKGBUILD: line 52: make: command not found
==> ERROR: A failure occurred in prepare().
    Aborting...
 -> error making: zyn-fusion
Press any key to continue...
[steve@steve-10rs003ruk ~]$ 
[steve@steve-10rs003ruk ~]$

**Comment by fundamental** [comment]
Thanks for reaching out. Looks like this is a bug in a downstream packaging script, notably `make: command not found`, so the PKGBUILD doesn't list a make tool as a build dependency. We do not maintain downstream PKGBUILD scripts, so you'll have to raise this issue with them.

**Comment by kx05ymu** [comment]
Thanks for your help.

**Comment by kx05ymu** [comment]
I've just used Pacman to do the install rather than Ocatavi/yay and it's worked. I noticed that make was listed in the dependencies this time.

Thanks again for taking the time to offer your advice.
